name: Build and Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
